# -*- mode: r by -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  INCLUDE_PRESEED = ENV['INCLUDE_PRESEED']

  config.vm.box = "image-builder"
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.vm.synced_folder "/tmp", "/vagrant", disabled: 'true'
  config.vm.provision "file", source: "../../packer/base-deb/http/preseed-helloworld.cfg", destination: "/tmp/preseed.cfg"
  config.vm.provision "file", source: "../../packer/base-deb/http/init", destination: "/tmp/init"
  config.vm.provision "file", source: "../../packer/base-deb/http/sbin_init", destination: "/tmp/sbin_init"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    sudo apt-get install -y python3 python3-pip
  SHELL
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/build-image.yml"
    ansible.extra_vars = {
      include_preseed: INCLUDE_PRESEED
    }
  end
end
